"""llama-swap client.

llama-swap is not just an OpenAI-compatible endpoint — it is a model *router*
that loads models on demand and evicts them on a TTL. Icarus leans on the parts
a generic OpenAI client ignores:

  /v1/models   what can be run at all
  /running     what is resident right now (and the exact llama-server argv)
  /unload      free VRAM without waiting for the TTL
  /health      liveness

It also reads llama-swap's own config.yaml, which is the only place the real
per-model context window is recorded *before* a model is loaded.
"""

from __future__ import annotations

import json
import re
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

# Fallback when llama-swap's config is unreadable and the model isn't running.
# Deliberately conservative: over-estimating context is what causes a hard
# server-side truncation mid-conversation.
DEFAULT_CTX = 8192


@dataclass
class ModelInfo:
    id: str
    ctx: int = DEFAULT_CTX
    loaded: bool = False
    state: str = ""
    # Human-facing extras parsed out of the llama-swap config when present.
    size_note: str = ""
    gpus: str = ""
    ttl: Optional[int] = None


@dataclass
class SwapClient:
    base_url: str = "http://127.0.0.1:9292/v1"
    config_path: str = ""
    timeout: int = 15
    _ctx_cache: Dict[str, int] = field(default_factory=dict)
    _cfg_mtime: float = 0.0

    # ---- plumbing -------------------------------------------------------
    @property
    def root(self) -> str:
        """Management endpoints live at the host root, not under /v1."""
        return re.sub(r"/v1/?$", "", self.base_url)

    def _get(self, path: str, timeout: Optional[int] = None) -> Any:
        req = urllib.request.Request(
            f"{self.root}{path}", headers={"Accept": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=timeout or self.timeout) as r:
            body = r.read().decode("utf-8", "replace")
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            return body

    # ---- liveness -------------------------------------------------------
    def healthy(self) -> bool:
        try:
            self._get("/health", timeout=5)
            return True
        except Exception:
            return False

    # ---- context windows ------------------------------------------------
    def _load_ctx_from_config(self) -> Dict[str, int]:
        """Parse --ctx-size out of each model's launch command.

        llama-swap's config is auto-generated by gen_config.py and rewritten on
        model changes, so we re-read whenever its mtime moves.
        """
        p = Path(self.config_path or "")
        if not p.is_file():
            return {}
        try:
            mtime = p.stat().st_mtime
            if self._ctx_cache and mtime == self._cfg_mtime:
                return self._ctx_cache
            raw = yaml.safe_load(p.read_text()) or {}
        except Exception:
            return self._ctx_cache

        out: Dict[str, int] = {}
        for name, spec in (raw.get("models") or {}).items():
            cmd = (spec or {}).get("cmd", "") if isinstance(spec, dict) else ""
            m = re.search(r"--ctx-size\s+(\d+)", str(cmd))
            if m:
                out[name] = int(m.group(1))
        self._ctx_cache, self._cfg_mtime = out, mtime
        return out

    def context_window(self, model: str) -> int:
        """Real context window for a model, preferring live truth over config."""
        for r in self.running():
            if r.get("model") == model:
                m = re.search(r"--ctx-size\s+(\d+)", r.get("cmd", ""))
                if m:
                    return int(m.group(1))
        return self._load_ctx_from_config().get(model, DEFAULT_CTX)

    # ---- inventory ------------------------------------------------------
    def list_models(self) -> List[str]:
        try:
            data = self._get("/v1/models")
            return sorted(m["id"] for m in (data.get("data") or []))
        except Exception:
            return []

    def running(self) -> List[Dict[str, Any]]:
        try:
            return self._get("/running").get("running") or []
        except Exception:
            return []

    def loaded_models(self) -> List[str]:
        return [r.get("model", "") for r in self.running()]

    def inventory(self) -> List[ModelInfo]:
        """Everything the picker needs, in one pass."""
        ctxs = self._load_ctx_from_config()
        live = {r.get("model"): r for r in self.running()}
        raw_cfg: Dict[str, Any] = {}
        p = Path(self.config_path or "")
        if p.is_file():
            try:
                raw_cfg = (yaml.safe_load(p.read_text()) or {}).get("models") or {}
            except Exception:
                raw_cfg = {}

        out: List[ModelInfo] = []
        for mid in self.list_models():
            spec = raw_cfg.get(mid) or {}
            cmd = str(spec.get("cmd", "")) if isinstance(spec, dict) else ""
            env = spec.get("env") or [] if isinstance(spec, dict) else []
            gpus = ""
            for e in env:
                g = re.match(r"CUDA_VISIBLE_DEVICES=(.*)", str(e))
                if g:
                    gpus = g.group(1)
            ctx = ctxs.get(mid, DEFAULT_CTX)
            if mid in live:
                m = re.search(r"--ctx-size\s+(\d+)", live[mid].get("cmd", ""))
                if m:
                    ctx = int(m.group(1))
            out.append(
                ModelInfo(
                    id=mid,
                    ctx=ctx,
                    loaded=mid in live,
                    state=live.get(mid, {}).get("state", ""),
                    size_note=_size_hint(cmd),
                    gpus=gpus,
                    ttl=spec.get("ttl") if isinstance(spec, dict) else None,
                )
            )
        return out

    def resolve(self, fragment: str) -> Optional[str]:
        """Map a user-typed fragment to exactly one model id.

        Exact match wins; then prefix; then substring. Ambiguous substrings
        return None so the caller can show the candidates instead of guessing.
        """
        models = self.list_models()
        if fragment in models:
            return fragment
        low = fragment.lower()
        for pool in (
            [m for m in models if m.lower().startswith(low)],
            [m for m in models if low in m.lower()],
        ):
            if len(pool) == 1:
                return pool[0]
            if len(pool) > 1:
                return None
        return None

    def candidates(self, fragment: str) -> List[str]:
        low = fragment.lower()
        return [m for m in self.list_models() if low in m.lower()]

    # ---- lifecycle ------------------------------------------------------
    def unload_all(self) -> bool:
        try:
            self._get("/unload", timeout=30)
            return True
        except Exception:
            return False

    def wait_unloaded(self, model: str = "", timeout: int = 60, poll: float = 0.5) -> bool:
        """Block until a model (or everything) has finished unloading.

        llama-swap answers requests with HTTP 500 "matrix is shutting down"
        while a teardown is in flight, so anything that unloads must wait for
        it to finish before letting the next request through.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            live = self.loaded_models()
            if (model and model not in live) or (not model and not live):
                return True
            time.sleep(poll)
        return False

    def wait_ready(self, model: str, timeout: int = 600, poll: float = 1.5) -> bool:
        """Block until `model` reports ready. Cold loads of a 35B take minutes."""
        deadline = time.time() + timeout
        while time.time() < deadline:
            for r in self.running():
                if r.get("model") == model and r.get("state") == "ready":
                    return True
            time.sleep(poll)
        return False


def _size_hint(cmd: str) -> str:
    """Pull the model filename out of the launch command for display."""
    m = re.search(r"--model\s+(\S+)", cmd)
    if not m:
        return ""
    name = Path(m.group(1)).name
    # Ollama blobs are opaque sha256 names; nothing useful to show.
    return "" if name.startswith("sha256-") else name
